# 1. Calculate n-step Transition Probability(Chapman-        Kolmogrov eq.)


Que. 1.1. Consider a finite Markov Chain {Xn,n ≥ 0} with state space S = {1,2} and transition probability
matrix(TPM) P1 as given below and initial probability distribution is [α1 = 0.35,α2 = 0.65]. Obtain
the following terms.i) P(2)_12  ii) P(4)_11  iii) P(X27 = 1|X17 = 2)  iv) P(X5 = 1) v) P(X8 = 2)

In [1]:
import numpy as np
import pandas as pd
from numpy.linalg import matrix_power

In [25]:
alpha1=np.array([0.35,0.65])
P1=np.array([[0.70,0.3],[0.4,0.6]])
P1

array([[0.7, 0.3],
       [0.4, 0.6]])

In [27]:
#i) P(2)_12
P_2=matrix_power(P1,2)
P_2[0,1]

0.39

In [4]:
#ii) P(4)_11
P_4=matrix_power(P1,4)
P_4[0,0]

0.5748999999999999

In [5]:
#iii) P(X27 = 1|X17 = 2) 
P_10=matrix_power(P1,10)
P_10[1,0]

0.5714251971999998

In [6]:
#iv) P(X5 = 1)
P_5=matrix_power(P1,5)
P_5
np.dot(alpha1,P_5)[0]

0.5708904999999999

In [7]:
# v) P(X8 = 2)
P_8=matrix_power(P1,8)
P_8
np.dot(alpha1,P_8)[1]

0.4285859565

Que 1.2. Consider a finite Markov Chain {Xn,n ≥ 0} with state space S = {0,1,2,3} and TPM P2 as given below. Obtain the following terms. i) P(8)11 ii) P(X8 = 2|X3 = 2) iii) P(X4 = 2) iv) P(X6 = 2)where initial probability distribution is [α0,α1,α2,α3] =[0.1,0.2,0.3,0.4] ·

In [8]:
alpha2=np.array([0.1,0.2,0.3,0.4] )
P2=np.array([[0.3, 0.5, 0.1, 0.1],
             [0.1, 0.6, 0.1, 0.2],
             [ 0,  0.5, 0.5,  0 ],
             [ 0,  0.3, 0.2, 0.5]])
P2

array([[0.3, 0.5, 0.1, 0.1],
       [0.1, 0.6, 0.1, 0.2],
       [0. , 0.5, 0.5, 0. ],
       [0. , 0.3, 0.2, 0.5]])

In [9]:
#i) P(8)11
P_8=matrix_power(P2,8)
P_8[1,1]

0.5071403400000001

In [10]:
#ii) P(X8 = 2|X3 = 2)
P_5=matrix_power(P2,5)
P_5[2,2]

0.20305

In [12]:
# iii) P(X4 = 2)
P_4=matrix_power(P2,4)
P_4
np.dot(alpha2,P_4)[2]

0.20673000000000002

In [13]:
#iv) P(X6 = 2)
P_6=matrix_power(P2,6)
np.dot(alpha2,P_6)[2]

0.20326550000000002

# 2. Realization of Markov Chain 

Que 2.1. Consider a finite Markov Chain {Xn,n ∈ N} with state space S = {1,2,3,4} and TPM is P1 and initial probabilities are α = [α1,α2,α3,α4] = [0.1,0.2,0.3,0.4]. Generate the above Markov Chain up to n=5. (i.e. Obtain the realization X0,X1,··· ,X5)

In [14]:
P2=np.array([[0.5, 0.5,  0,   0 ],
            [ 0,  0.3, 0.3, 0.5],
            [0.2, 0.2, 0.4, 0.2],
            [ 1,  0,   0,    0 ]])
P2

array([[0.5, 0.5, 0. , 0. ],
       [0. , 0.3, 0.3, 0.5],
       [0.2, 0.2, 0.4, 0.2],
       [1. , 0. , 0. , 0. ]])

In [15]:
a=[0.1,0.2,0.3,0.4]
a

[0.1, 0.2, 0.3, 0.4]

In [16]:
s=[1,2,3,4]
s


[1, 2, 3, 4]

In [17]:
x=np.array([0,0,0,0,0])
x

array([0, 0, 0, 0, 0])

In [18]:
from numpy import random

In [19]:
x[0]=np.random.choice(s,p=a)
n=[0,1,2,3]
for i in n:
    x[i+1]=np.random.choice(s,p=a)
print('Markov chain upto n=5 is',x)

Markov chain upto n=5 is [4 4 1 4 4]


Que 2.2. Consider a finite Markov Chain {Xn,n ∈ N} with state space S = {1,2,3} and transition probability matrix is P2 and initial probabilities are α = [0.3,0.5,0.2] Generate the above Markov Chain up to n = 5.

In [20]:
P2=np.array([[0.3,0.2,0.5],
             [0.2,0.5,0.3],
             [0.3,0.4,0.3]])
P2

array([[0.3, 0.2, 0.5],
       [0.2, 0.5, 0.3],
       [0.3, 0.4, 0.3]])

In [21]:
a1=[0.3,0.5,0.2]
a1

[0.3, 0.5, 0.2]

In [22]:
s1=[1,2,3]
x1=np.array([0,0,0,0,0])

In [23]:
x1[0]=np.random.choice(s1,p=a1)
n=[0,1,2,3]
for i in n:
    x[i+1]=np.random.choice(s1,p=a1)
print('Markov chain upto n=5 is',x1)

Markov chain upto n=5 is [1 0 0 0 0]
